- frontend/src/components/chip-selection/ChipSelection.tsx
- frontend/src/components/menu/Menu.tsx
Issue: [C4R-134]( https://wearetribus.atlassian.net/browse/C4R-134
Chip Selection component:
- template for selection component
- prop types
- selection handling
> Chip selection component

- backend/nest-cli.json
- backend/package.json
- backend/src/common/constants/patterns.constant.ts
- backend/src/modules/organization/dto/create-contact.dto.ts
- backend/src/modules/organization/dto/create-organization-activity.dto.ts
- backend/src/modules/organization/dto/create-organization-financial.dto.ts
- backend/src/modules/organization/dto/create-organization-general.dto.ts
- backend/src/modules/organization/dto/create-organization-legal.dto.ts
- backend/src/modules/organization/dto/create-organization-report.dto.ts
- backend/src/modules/organization/dto/create-organization.dto.ts
- backend/src/modules/organization/dto/inverstor.dto.ts
- backend/src/modules/organization/dto/investor.dto.ts
- backend/src/modules/organization/dto/person.dto.ts
- backend/src/modules/organization/dto/report.dto.ts
- backend/src/modules/organization/dto/update-contact.dto.ts
- backend/src/modules/organization/dto/update-organization-general.dto.ts
- backend/src/modules/organization/dto/update-organization-legal.dto.ts
- backend/src/modules/organization/dto/update-organization.dto.ts
- backend/src/modules/organization/entities/organization-report.entity.ts
- added dto validation for every dto so far
- switched from manual swagger decorators to swagger plugin to reduce boilerplate
> feat: [C4R-154] added dto validation

- backend/package-lock.json
- backend/package.json
- backend/src/common/constants/error-common.constants.ts
- backend/src/libs/bull-board.ts
- backend/src/main.ts
npm install --save @bull-board/api
npm install --save @bull-board/express
> feat: [C4R-189] added BullBoard for queue management

- frontend/.linguirc
- frontend/README.md
- frontend/package-lock.json
- frontend/package.json
- frontend/src/App.tsx
- frontend/src/assets/locales/en/messages.js
- frontend/src/assets/locales/en/messages.json
- frontend/src/assets/locales/ro/messages.js
- frontend/src/assets/locales/ro/messages.json
- frontend/src/common/enums/language.enum.ts
- frontend/src/components/menu/Menu.tsx
- frontend/src/containers/Layout.tsx
- frontend/src/contexts/LocaleContext.tsx
Issue: [C4R-210]( https://wearetribus.atlassian.net/browse/C4R-210
Internationalization setup with linguijs
> I18n Setup

- backend/package-lock.json
- backend/package.json
- backend/src/common/constants/anaf.constants.ts
- backend/src/shared/interfaces/anaf.interface.ts
- backend/src/shared/services/anaf.service.ts
- backend/src/shared/services/index.ts
- backend/src/shared/shared.module.ts
npm install --save @nestjs/axios
> feat: [C4R-185] ANAF service

- backend/nest-cli.json
- backend/package-lock.json
- backend/package.json
- backend/src/app.module.ts
- backend/src/common/base/base-dao.class.ts
- backend/src/common/base/base-filter.dto.ts
- backend/src/common/decorators/roles.decorator.ts
- backend/src/common/enums/order-direction.enum.ts
- backend/src/common/interfaces/pagination-config.ts
- backend/src/modules/user/constants/user-filters.config.ts
- backend/src/modules/user/dto/create-user.dto.ts
- backend/src/modules/user/dto/update-user.dto.ts
- backend/src/modules/user/dto/user-filter.dto.ts
- backend/src/modules/user/entities/user.entity.ts
- backend/src/modules/user/enums/role.enum.ts
- backend/src/modules/user/enums/user-status.enum.ts
- backend/src/modules/user/repositories/user.repository.ts
- backend/src/modules/user/services/user.service.ts
- backend/src/modules/user/user.controller.ts
- backend/src/modules/user/user.module.ts
https://wearetribus.atlassian.net/browse/C4R-257
- Create User
- Update User
- Basic Validations
- Get Users
- Filters 
- Pagination
> Feature/c4 r 81 - User Management

- backend/src/libs/bull-board.ts
- backend/src/modules/user/services/user.service.ts
The logger from nestjs-pino is now being used for internal logging.
> feat: [C4R-334] backend now uses only one logger

- frontend/src/pages/organization/Organization.tsx
- frontend/src/pages/organization/components/OrganizationActivity/OrganizationActivity.tsx
- frontend/src/pages/organization/components/OrganizationFinancial/OrganizationFinancial.tsx
- frontend/src/pages/organization/components/OrganizationGeneral/OrganizationGeneral.tsx
- frontend/src/pages/organization/components/OrganizationLegal/OrganizationLegal.tsx
- frontend/src/pages/organization/enums/OrganizationStatus.enum.ts
- frontend/src/pages/organization/interfaces/Organization.interface.ts
- frontend/src/pages/users/enums/UserStatus.enum.ts
- frontend/src/pages/users/interfaces/User.interface.ts
- frontend/src/services/organization/Organization.queries.ts
- frontend/src/services/user/User.queries.ts
- frontend/src/store/organization/organization.selectors.ts
- frontend/src/store/organization/organization.slice.ts
- frontend/src/store/store.ts
- frontend/src/store/user/User.slice.ts
- Save organization data in state
- Request/Update ONG profile data based on saved organization
> feat[C4R-350] Request Organization from User Profile

- frontend/src/pages/organization/components/OrganizationLegal/OrganizationLegal.tsx
Fixed data being saved when deleting/cancelling deletion on director/other person of interest in Organization Legal.
> fixes: [C4R-344] fixed data being saved on delete

- backend/src/modules/application/application.controller.ts
- backend/src/modules/organization/organization.controller.ts
- backend/src/modules/user/services/user.service.ts
- backend/src/modules/user/user.controller.ts
- backend/src/shared/controllers/nomenclatures.controller.ts
- backend/src/shared/controllers/shared.controller.ts
Also removed a leftover pinologger(?).
> feat: [C4R-352] added missing swagger decorators

- backend/src/modules/user/admin-user.controller.ts
- backend/src/modules/user/dto/create-user.dto.ts
- backend/src/modules/user/entities/user.entity.ts
- backend/src/modules/user/services/user.service.ts
- frontend/src/AuthProvider.tsx
- frontend/src/common/router/Router.tsx
- frontend/src/components/card-panel/CardPanel.tsx
- frontend/src/components/content-wrapper/ContentWrapper.tsx
- frontend/src/index.css
- frontend/src/pages/organization/components/OrganizationActivity/OrganizationActivity.tsx
- frontend/src/pages/organization/components/OrganizationGeneral/OrganizationGeneral.tsx
- frontend/src/pages/organization/components/OrganizationLegal/OrganizationLegal.tsx
- frontend/src/pages/users/components/UserCreate.tsx
- frontend/src/pages/users/components/UserCreateConfig.ts
- frontend/src/pages/users/interfaces/UserPayload.interface.ts
- frontend/src/services/user/User.queries.ts
- frontend/src/services/user/User.service.ts
Task [C4R-81](https://wearetribus.atlassian.net/jira/software/c/projects/C4R/boards/6?modal=detail&selectedIssue=C4R-81&assignee=60f9333a9f975e0069d2df9e])
Changes:
- Add user template
- Update the card wrapper component to accept submit button
- Create a content wrapper component to have a single wrapper for all pages with title, subtitle, and back button
- Set employee user as active upon creation
- Cleanup and refactoring
> feature[C4R081] Add User

- backend/src/app.module.ts
- backend/src/modules/organization/constants/errors.constants.ts
- backend/src/modules/organization/organization.controller.ts
- backend/src/modules/organization/services/organization.service.ts
- backend/src/modules/requests/dto/create-request.dto.ts
- backend/src/modules/requests/entities/request.entity.ts
- backend/src/modules/requests/enums/request-status.enum.ts
- backend/src/modules/requests/repositories/request.repository.ts
- backend/src/modules/requests/requests.controller.ts
- backend/src/modules/requests/requests.module.ts
- backend/src/modules/requests/services/requests.service.ts
- backend/src/modules/user/admin-user.controller.ts
- backend/src/modules/user/entities/user.entity.ts
- backend/src/modules/user/services/user.service.ts
> Requests (create, approve, reject)

- backend/src/modules/organization/constants/values.constants.ts
- backend/src/modules/organization/dto/expense.dto.ts
- backend/src/modules/organization/dto/income.dto.ts
- frontend/src/pages/organization/components/OrganizationFinancial/components/ExpenseReportConfig.ts
- frontend/src/pages/organization/components/OrganizationFinancial/components/ExpenseReportModal.tsx
- frontend/src/pages/organization/components/OrganizationFinancial/components/IncomeReportConfig.ts
- frontend/src/pages/organization/components/OrganizationFinancial/components/IncomeReportModal.tsx
- frontend/src/pages/organization/constants/values.constants.tsx
C4R-364: the title of Income Report pop-up is invalid
C4R-365: edit button doesn't work on income report view
C4R-366: only positive numbers must be allowed
C4R-367: the fields have a value limit
C4R-368: textbox is expanding when a lot of (decimal) numbers are used
> fix: fixed some NGO Financial bugs

- backend/src/app.module.ts
- backend/src/common/guards/roles.guard.ts
- backend/src/modules/organization/organization-profile.controller.ts
- backend/src/modules/organization/organization.module.ts
- backend/src/modules/user/admin-user.controller.ts
- backend/src/modules/user/constants/user-error.constants.ts
- backend/src/modules/user/services/user.service.ts
- frontend/src/AuthProvider.tsx
- frontend/src/common/router/Routes.constants.ts
- frontend/src/components/menu/Menu.tsx
- frontend/src/contexts/AuthContext.tsx
- frontend/src/pages/organization/Organization.tsx
- frontend/src/pages/organization/components/OrganizationActivity/OrganizationActivity.tsx
- frontend/src/pages/organization/components/OrganizationData/OrganizationData.tsx
- frontend/src/pages/organization/components/OrganizationFinancial/OrganizationFinancial.tsx
- frontend/src/pages/organization/components/OrganizationFinancial/components/ExpenseReportModal.tsx
- frontend/src/pages/organization/components/OrganizationFinancial/components/IncomeReportModal.tsx
- frontend/src/pages/organization/components/OrganizationGeneral/OrganizationGeneral.tsx
- frontend/src/pages/organization/components/OrganizationLegal/OrganizationLegal.tsx
- frontend/src/pages/users/enums/UserRole.enum.ts
- frontend/src/services/organization/Organization.queries.ts
- frontend/src/services/organization/Organization.service.ts
Resolves
C4R-454: Employee Role Management
C4R-455: Super Admin Role Management
C4R-456: Admin Role Management
> Feature[448] Role Management 

- backend/src/modules/user/services/cognito.service.ts
- backend/src/modules/user/services/user.service.ts
- frontend/src/components/Select/Select.tsx
- frontend/src/components/date-range-picker/DateRangePicker.tsx
- frontend/src/services/request/Request.queries.ts
- frontend/src/services/user/User.queries.ts
Closes #XXX 
- C4R-432 - Update user cognito
- C4R-460 -Update user meta
- Update rangepicker and select placeholders
> Feature[C4R-92] Update cognito user data

- frontend/src/components/confim-removal-modal/ConfirmRemovalModal.tsx
- frontend/src/components/confim-removal-modal/ConfirmationModal.tsx
- frontend/src/index.css
- frontend/src/pages/account/Account.tsx
- frontend/src/pages/requests/components/Request.tsx
- frontend/src/pages/requests/components/RequestList.tsx
- frontend/src/pages/requests/constants/Request.modals.ts
- frontend/src/pages/users/components/UserList/UserList.tsx
> feat: [C4R-462] add confirmation modals for approve and reject requests

- frontend/src/pages/create-organziation/components/ProgressSteps.tsx
- frontend/src/pages/create-organziation/configs/CreateOrganizationUserConfig.ts
- C4R-399: updated the pattern to match the rest of the program
- C4R-436: the user was able to move through the form when the current step was not filled out (the list still appears clickable but is not, only way to progress is by clicking 'next' button)
> fix: invalid phone number, form skipping

- backend/src/common/base/base-dao.class.ts
- backend/src/common/interfaces/pagination-config.ts
- backend/src/modules/requests/constants/request-filters.config.ts
- backend/src/modules/requests/entities/request.entity.ts
- backend/src/modules/requests/enums/request-type.enum.ts
- backend/src/modules/requests/requests.controller.ts
- backend/src/modules/requests/services/requests.service.ts
- backend/src/modules/user/constants/user-error.constants.ts
- backend/src/modules/user/constants/user-filters.config.ts
- backend/src/modules/user/dto/create-user.dto.ts
- backend/src/modules/user/entities/user.entity.ts
- backend/src/modules/user/services/cognito.service.ts
- backend/src/modules/user/services/user.service.ts
- frontend/src/pages/requests/components/RequestList.headers.tsx
- frontend/src/pages/requests/interfaces/Request.interface.ts
- frontend/src/services/request/Request.service.ts
- frontend/src/store/request/Requests.slice.ts
Closes #XXX 
- C4R-493 - Refactor requests
> Feature[493] - Refactor request

- backend/src/modules/application/application.controller.ts
- backend/src/modules/application/application.module.ts
- backend/src/modules/application/constants/application-error.constants.ts
- backend/src/modules/application/entities/ong-application.entity.ts
- backend/src/modules/application/enums/ong-application-status.enum.ts
- backend/src/modules/application/repositories/ong-application.repository.ts
- backend/src/modules/application/services/ong-application.service.ts
- backend/src/modules/requests/constants/request-filters.config.ts
- backend/src/modules/requests/constants/requests-errors.constants.ts
- backend/src/modules/requests/dto/create-application-request.dto.ts
- backend/src/modules/requests/entities/request.entity.ts
- backend/src/modules/requests/enums/request-type.enum.ts
- backend/src/modules/requests/requests.controller.ts
- backend/src/modules/requests/requests.module.ts
- backend/src/modules/requests/services/requests.service.ts
Closes #XXX 
- Request Application Admin -> Super-Admin
- Get All app request
- Get App request by id
- Approve/Reject Application Request
- Get One Ong Application
> Feature[C4R-216] Application Requests

- frontend/src/common/guards/RoleGuard.tsx
- frontend/src/common/router/Router.tsx
C4R-458
Added a Role Guard + example for Router.
> feat: [C4R-458] add role guard

- frontend/src/common/router/Router.tsx
- frontend/src/common/router/Routes.constants.ts
- frontend/src/pages/apps-store/components/AddApplication.tsx
- frontend/src/pages/users/Users.tsx
tasks:
[C4R-583] https://wearetribus.atlassian.net/browse/C4R-583
[C4R-606] https://wearetribus.atlassian.net/browse/C4R-606
[C4R-582] https://wearetribus.atlassian.net/browse/C4R-582
+ fixed the "add user" button on user list -> it was visible for super admin and it should have been for admin only.
> feat: [C4R-583] added route guards

- frontend/src/index.css
- frontend/src/pages/application/components/ApplicationDetails.tsx
- frontend/src/pages/my-apps/components/ApplicationCard.tsx
- frontend/src/pages/requests/interfaces/OngApplication.interface.ts
[C4R-623] https://wearetribus.atlassian.net/browse/C4R-623
[C4R-622] https://wearetribus.atlassian.net/browse/C4R-622
> feat: [C4R-623] add "indisponibil" ribbon

- frontend/src/pages/requests/constants/Request.modals.ts
- C4R-665: approval
- C4R-666: rejection
> fix [C4R-665]: fixed request approval and rejection text

- frontend/src/pages/create-organziation/CreateOrganization.tsx
- frontend/src/pages/organization/components/OrganizationActivity/OrganizationActivityConfig.ts
Also a small fix on create organization internationalization.
> fix: [C4R-452] certain fields could be skipped in step 3 of create org

- backend/src/mail/enums/mail.enum.ts
- backend/src/mail/templates/delete-ong-application-request.hbs
- backend/src/modules/application/application.module.ts
- backend/src/modules/application/controllers/application-request.controller.ts
- backend/src/modules/application/controllers/application.controller.ts
- backend/src/modules/application/enums/ong-application-status.enum.ts
- backend/src/modules/application/services/application.service.ts
- backend/src/modules/organization/controllers/organization-application.controller.ts
- backend/src/modules/user/services/user.service.ts
- backend/src/modules/user/user.module.ts
- frontend/src/assets/locales/ro/translation.json
- frontend/src/pages/application/components/ApplicationDetails.tsx
- frontend/src/pages/application/components/ApplicationNGOList.tsx
- frontend/src/pages/apps-store/constants/ApplicationStatus.constant.ts
- frontend/src/pages/requests/interfaces/OngApplication.interface.ts
- frontend/src/pages/users/components/ApplicationAccessManagement.tsx
- frontend/src/services/application/Application.queries.ts
- frontend/src/services/application/Application.service.ts
Closes #XXX 
- [C4R-87](https://wearetribus.atlassian.net/browse/C4R-87) Remove application / Request application removal flow
> Feature[C4R-87] Remove application request

- backend/src/modules/application/services/ong-application.service.ts
- backend/src/modules/organization/constants/errors.constants.ts
- backend/src/modules/organization/controllers/organization.controller.ts
- backend/src/modules/organization/entities/investor.entity.ts
- backend/src/modules/organization/entities/partner.entity.ts
- backend/src/modules/organization/entities/report.entity.ts
- backend/src/modules/organization/services/organization-financial.service.ts
- backend/src/modules/organization/services/organization.service.ts
- backend/src/shared/services/anaf.service.ts
Inserts 2 new entries in OrganizationFinancial Table (one for Expense and one for Income) for the currentYear - 1;
Inserts 1 new entry in Report table for currentYear
Inserts 1 new entry in Investor Table for currentYear
Inserts 1 new entry in Partner Table for currentYear
> feat: [C4R-679] API to create new reporting entries for last year

- frontend/src/pages/create-organziation/components/CreateOrganizationGeneral.tsx
- frontend/src/pages/create-organziation/components/CreateOrganizationUser.tsx
> fix: C4R-698, C4R-696 removed 1st step back button

- backend/src/common/decorators/form-data-body.decorator.ts
- backend/src/common/decorators/to-boolean.decorator.ts
- backend/src/modules/organization/controllers/organization.controller.ts
- backend/src/modules/organization/dto/create-organization-activity.dto.ts
- backend/src/modules/organization/dto/create-organization-general.dto.ts
- backend/src/modules/organization/dto/update-organization-financial.dto.ts
- backend/src/modules/organization/dto/update-organization-report.dto.ts
[C4R-452](https://wearetribus.atlassian.net/browse/C4R-452) - Validation Issues on FE at 3rd step from profile creation
Changes:
- Custom string to boolean conversion decorator
- Custom form data body parser decorator
- Update type castings on create/update organization dto
> Bugfix[C4R-452] Create Organization fails with missing federations

- backend/src/modules/organization/controllers/organization-profile.controller.ts
- frontend/src/pages/create-organziation/CreateOrganization.tsx
- frontend/src/pages/create-organziation/components/CreateOrganizationActivity.tsx
- frontend/src/pages/organization/components/OrganizationActivity/OrganizationActivity.tsx
- frontend/src/pages/organization/components/OrganizationActivity/OrganizationActivityConfig.ts
- parse boolean body data on organization-profile PATCH endpoint
- consistent data handling on create organization navigation between steps
- add missing required validations on organization-activity form.
> Bugfix[C4R-452] Invalid data organization activity

- frontend/src/pages/application/ApplicationWithOngList.tsx
- frontend/src/pages/apps-store/AllApplications.tsx
- frontend/src/pages/organization/Organization.tsx
- frontend/src/pages/organization/OrganizationProfile.tsx
- frontend/src/pages/requests/components/Request.tsx
- frontend/src/pages/users/Users.tsx
Name is needed in the state to be displayed in the dropdown menu component.
[C4R-857](https://wearetribus.atlassian.net/browse/C4R-857)
> fix: [C4R-857] fixed mobile menu dropdown menu selection

- backend/src/modules/practice-program/controllers/practice-program.controller.ts
- backend/src/modules/practice-program/dto/create-practice-program.dto.ts
- backend/src/modules/practice-program/services/practice-program.service.ts
- frontend/src/assets/locales/ro/translation.json
- frontend/src/common/router/Router.tsx
- frontend/src/pages/pactice-program/CreatePracticeProgram.tsx
- frontend/src/pages/pactice-program/EditPracticeProgram.tsx
- frontend/src/pages/pactice-program/components/PracticeProgramForm.tsx
- frontend/src/services/practice-program/PracticeProgram.helper.ts
- frontend/src/services/practice-program/PracticeProgram.queries.ts
- frontend/src/services/practice-program/PracticeProgram.service.ts
- frontend/src/services/practice-program/interfaces/practice-program-payload.interface.ts
[C4R-764](https://wearetribus.atlassian.net/browse/C4R-764) - Update practice program part
Changes:
- Update practice program page with validations
- Api integration
Openes issue for select not loading default values for city and faculties [here](https://wearetribus.atlassian.net/browse/C4R-860)
> Feature[C4R-792] Update Practice program

- backend/src/modules/organization/constants/errors.constants.ts
- backend/src/modules/organization/constants/organization-filter.config.ts
- backend/src/modules/organization/controllers/organization.controller.ts
- backend/src/modules/organization/dto/get-organization-with-practice-programs-fillter.dto.ts
- backend/src/modules/organization/interfaces/OrganizationFlat.interface.ts
- backend/src/modules/organization/services/organization.service.ts
- [C4R-842](https://wearetribus.atlassian.net/browse/C4R-842) Search organizations with active practice programs
> Feature[C4R-842] Search Organizations with practice programs

- backend/src/modules/_publicAPI/public-api.controller.ts
- backend/src/modules/_publicAPI/public-api.module.ts
- backend/src/modules/_publicAPI/services/civic-center-public.service.ts
- backend/src/modules/civic-center-service/civic-center.module.ts
- backend/src/modules/civic-center-service/constants/civic-center-filters.config.ts
- backend/src/modules/civic-center-service/constants/errors.constants.ts
- backend/src/modules/civic-center-service/controllers/civic-center.controller.ts
- backend/src/modules/civic-center-service/dto/civic-center-service-search-filter.dto.ts
- backend/src/modules/civic-center-service/services/civic-center.service.ts
- backend/src/modules/practice-program/services/practice-program.service.ts
[C4R-790](https://wearetribus.atlassian.net/browse/C4R-790)  Search Services
> Feature[C4R-790] Search Services

- backend/src/modules/organization/dto/create-organization-request.dto.ts
- backend/src/modules/organization/services/organization-request.service.ts
- backend/src/modules/organization/services/organization.service.ts
- frontend/src/pages/create-organziation/components/CreateOrganizationGeneral.tsx
[C4R-431](https://wearetribus.atlassian.net/browse/C4R-431)
> fix: [C4R-431] person of contact duplicated in create organization

- backend/src/common/decorators/validation.decorator.ts
- backend/src/modules/user/services/user.service.ts
[C4R-513](https://wearetribus.atlassian.net/browse/C4R-513)
> fix: [C4R-513] format phone number for RO

- backend/src/modules/user/admin-user.controller.ts
- frontend/src/pages/organization/components/Overview/OrganizationOverview.tsx
- frontend/src/pages/users/components/UserList/UserList.tsx
- frontend/src/services/user/User.queries.ts
- frontend/src/services/user/User.service.ts
[C4R-813](https://wearetribus.atlassian.net/browse/C4R-813)
> fix: [C4R-813] user table gets all users on ong overview

- backend/src/modules/organization/entities/organization-view.entity.ts
- backend/src/modules/statistics/services/statistics.service.ts
[C4R-697](https://wearetribus.atlassian.net/browse/C4R-697)
> fix: [C4R-697] fixed ong user count

- backend/src/modules/_publicAPI/controllers/civic-center-public.controller.ts
- backend/src/modules/_publicAPI/controllers/public-api.controller.ts
- backend/src/modules/_publicAPI/public-api.controller.ts
- backend/src/modules/_publicAPI/public-api.module.ts
- backend/src/modules/_publicAPI/services/civic-center-public.service.ts
- backend/src/modules/civic-center-service/services/civic-center.service.ts
- backend/src/modules/organization/constants/errors.constants.ts
- backend/src/modules/organization/constants/organization-filter.config.ts
- backend/src/modules/organization/dto/get-organization-with-services-filter.dto.ts
- backend/src/modules/organization/entities/organization-view.entity.ts
- backend/src/modules/organization/interfaces/OrganizationWithServices.interface.ts
- backend/src/modules/organization/organization.module.ts
- backend/src/modules/organization/services/organization.service.ts
- backend/src/modules/statistics/services/statistics.service.ts
- backend/src/modules/user/admin-user.controller.ts
- frontend/src/pages/organization/components/Overview/OrganizationOverview.tsx
- frontend/src/pages/users/components/UserList/UserList.tsx
- frontend/src/services/user/User.queries.ts
- frontend/src/services/user/User.service.ts
[C4R-950](https://wearetribus.atlassian.net/browse/C4R-950) Get organization with services
> Feature[C4R-950] Get Organization with services

- frontend/src/pages/application/components/ApplicationDetails.tsx
[C4R-837](https://wearetribus.atlassian.net/browse/C4R-837)
> fix: [C4R-837] removed request and delete app button for employee

- backend/src/modules/civic-center-service/constants/errors.constants.ts
- backend/src/modules/civic-center-service/controllers/civic-center.controller.ts
- backend/src/modules/civic-center-service/services/civic-center.service.ts
- frontend/src/pages/civic-center-service/components/CivicCenterServiceActions.tsx
- frontend/src/services/civic-center-service/CivicCenterService.queries.ts
- frontend/src/services/civic-center-service/CivicCenterService.service.ts
[C4R-876](https://wearetribus.atlassian.net/browse/C4R-876) Enable/Disable service
> Feature[C4R-876] Enable/Disable service

- frontend/src/assets/locales/ro/translation.json
https://wearetribus.atlassian.net/browse/C4R-807
> [C4R-807] Fix Create NGO Error message

- backend/src/modules/civic-center-service/constants/errors.constants.ts
- backend/src/modules/civic-center-service/controllers/civic-center.controller.ts
- backend/src/modules/civic-center-service/services/civic-center.service.ts
- frontend/src/assets/locales/ro/translation.json
- frontend/src/components/card-actions/CardActions.tsx
- frontend/src/pages/civic-center-service/CivicCenterCenterList.tsx
- frontend/src/pages/civic-center-service/components/CivicCenterServiceActions.tsx
- frontend/src/pages/pactice-program/components/PracticeProgramActions.tsx
- frontend/src/services/civic-center-service/CivicCenterService.queries.ts
- frontend/src/services/civic-center-service/CivicCenterService.service.ts
[C4R-877](https://wearetribus.atlassian.net/browse/C4R-877) Delete service
> Feature[C4R-877] Delete service

- backend/src/modules/_publicAPI/controllers/public-api.controller.ts
Needed for [C4R-818](https://wearetribus.atlassian.net/browse/C4R-818)
> feat: [C4R-818] removed hmac

- frontend/src/pages/users/components/UserCreate/UserCreate.tsx
[C4R-803](https://wearetribus.atlassian.net/browse/C4R-803)
> fix: [C4R-803] page freezing on user invite

- backend/src/modules/_publicAPI/controllers/public-api.controller.ts
- backend/src/modules/_publicAPI/dto/contact-mail.dto.ts
[C4R-909](https://wearetribus.atlassian.net/browse/C4R-909)
necessary BE changes with the addition of a new variable
> feat: [C4R-909] updated mail subject

- backend/src/modules/_publicAPI/public-api.module.ts
- backend/src/modules/practice-program/controllers/practice-program.controller.ts
- frontend/src/assets/locales/ro/translation.json
- frontend/src/common/router/Router.tsx
- frontend/src/pages/organization/components/OrganizationPracticePrograms/OrganizationPracticePrograms.tsx
- frontend/src/pages/organization/constants/Tabs.constants.tsx
- frontend/src/pages/pactice-program/CreatePracticeProgram.tsx
- frontend/src/pages/pactice-program/EditPracticeProgram.tsx
- frontend/src/pages/pactice-program/components/PracticeProgramsList.tsx
- frontend/src/services/practice-program/interfaces/practice-program-payload.interface.ts
[C4R-770](https://wearetribus.atlassian.net/browse/C4R-770) Practice programs for super-admin
> Feature[C4R-770] Practice programs for super-admin

- backend/src/modules/civic-center-service/controllers/civic-center.controller.ts
- backend/src/modules/civic-center-service/services/civic-center.service.ts
- backend/src/modules/practice-program/controllers/practice-program.controller.ts
- backend/src/modules/practice-program/services/practice-program.service.ts
- frontend/src/common/router/Router.tsx
- frontend/src/pages/civic-center-service/CreateCivicCenterService.tsx
- frontend/src/pages/civic-center-service/EditCivicCenterService.tsx
- frontend/src/pages/organization/components/OrganizationPracticePrograms/OrganizationPracticePrograms.tsx
- frontend/src/pages/organization/components/OrganizationServices/OrganizationServices.tsx
- frontend/src/pages/pactice-program/components/PracticeProgramsList.tsx
- frontend/src/services/civic-center-service/interfaces/civic-center-service-payload.interface.ts
- frontend/src/services/civic-center-service/interfaces/civic-center-service.interface.ts
[C4R-789](https://wearetribus.atlassian.net/browse/C4R-789) Services for Super-Admin
> Feature[C4R-789] Services for Super-Admin

- backend/src/modules/application/services/application.service.ts
https://wearetribus.atlassian.net/browse/C4R-830
> fix: [C4R-830] fix independent apps on this bug

- backend/src/modules/organization/entities/organization-request.entity.ts
- backend/src/modules/organization/services/organization-request.service.ts
- frontend/src/pages/requests/components/RequestList.headers.tsx
- frontend/src/pages/requests/interfaces/Request.interface.ts
[C4R-669](https://wearetribus.atlassian.net/browse/C4R-669)
> fix: [C4R-669] org logo missing from request table

- backend/src/modules/application/dto/create-application.dto.ts
- backend/src/modules/application/entities/application-history.entity.ts
- backend/src/modules/application/entities/application.entity.ts
- frontend/src/pages/apps-store/components/AddApplicationConfig.ts
- frontend/src/pages/apps-store/components/ApplicationForm.tsx
[C4R-922](https://wearetribus.atlassian.net/browse/C4R-922)
> fix: [C4R-922] application steps are now optional

- frontend/src/assets/locales/ro/translation.json
- frontend/src/components/menu/Menu.tsx
[C4R-859](https://wearetribus.atlassian.net/browse/C4R-859)
> fix: [C4R-859] removed informations option from sidemenu

- frontend/src/assets/locales/ro/translation.json
- frontend/src/components/data-table-filters/DataTableFilters.tsx
- frontend/src/components/date-range-picker/DateRangePicker.tsx
- frontend/src/pages/organization/Organizations.tsx
- frontend/src/pages/users/components/UserInvites/UserInvites.tsx
- frontend/src/pages/users/components/UserList/UserList.tsx
[C4R-874](https://wearetribus.atlassian.net/browse/C4R-874)
> fix: [C4R-874] reset filters button would not reset date

- backend/src/modules/civic-center-service/services/civic-center.service.ts
[C4R-973](https://wearetribus.atlassian.net/browse/C4R-973)
> fix: [C4R-973] API not sending civic service short description

- backend/src/modules/organization/constants/organization-filter.config.ts
[C4R-976](https://wearetribus.atlassian.net/browse/C4R-976)
> fix: [C4R-976] missing logo for ONG

- frontend/src/pages/pactice-program/components/PracticeProgramActions.tsx
[C4R-900](https://wearetribus.atlassian.net/browse/C4R-900)
> feature: [C4R-900] redirect from ONG hub to P4G website to view one program

- frontend/src/pages/civic-center-service/components/CivicCenterServiceActions.tsx
[C4R-966](https://wearetribus.atlassian.net/browse/C4R-966)
> feat: [C4R-966] redirect from ONG hub to CC website to view one service

- backend/src/modules/application/constants/application-error.constants.ts
- backend/src/modules/application/services/application.service.ts
- backend/src/modules/organization/services/organization-general.service.ts
- backend/src/modules/organization/services/organization-legal.service.ts
- backend/src/modules/organization/services/organization-report.service.ts
- backend/src/modules/organization/services/organization-request.service.ts
- backend/src/modules/organization/services/organization.service.ts
- backend/src/shared/constants/file-errors.constants.ts
- backend/src/shared/constants/file.constants.ts
- backend/src/shared/enum/FileType.enum.ts
- backend/src/shared/services/file-manager.service.ts
- frontend/src/assets/locales/ro/translation.json
- frontend/src/common/constants/error.constants.ts
- frontend/src/pages/apps-store/components/AddApplication.tsx
- frontend/src/pages/create-organziation/CreateOrganization.tsx
- frontend/src/pages/create-organziation/constants/CreateOrganizationErrors.constant.ts
- frontend/src/pages/organization/components/OrganizationGeneral/OrganizationGeneral.tsx
- frontend/src/pages/organization/components/OrganizationLegal/OrganizationLegal.tsx
[C4R-745](https://wearetribus.atlassian.net/browse/C4R-745)
[C4R-486](https://wearetribus.atlassian.net/browse/C4R-486)
[C4R-484](https://wearetribus.atlassian.net/browse/C4R-484)
[C4R-476](https://wearetribus.atlassian.net/browse/C4R-476)
> fix: [C4R-745, C4R-486, C4R-484, C4R-476] invalid files could be uploaded

- frontend/src/assets/locales/ro/translation.json
- frontend/src/components/menu/SlidingMenu.tsx
[C4R-859](https://wearetribus.atlassian.net/browse/C4R-859)
> fix: [C4R-859] removed informations option from menu

- frontend/src/pages/users/components/UserEdit/UserEdit.tsx
[C4R-803](https://wearetribus.atlassian.net/browse/C4R-803)
> fix: [C4F-803] forgot to add the freezing page fix to user edit

- backend/src/modules/application/services/application.service.ts
https://wearetribus.atlassian.net/browse/C4R-702
> C4R-702 - Status Pending Apps in NGO Profile - > Apps

- backend/src/modules/organization/entities/organization-view.entity.ts
[C4R-800](https://wearetribus.atlassian.net/browse/C4R-800) add filter for status when getting organization
> [C4R-800] Get all ONG's with status other than pending

- backend/src/shared/services/file-manager.service.ts
[C4R-1037](https://wearetribus.atlassian.net/browse/C4R-1037)
> fix: [C4R-1037] added check for files existence

- backend/src/modules/practice-program/constants/errors.constants.ts
- backend/src/modules/practice-program/services/practice-program.service.ts
- frontend/src/components/InputField/InputField.tsx
- frontend/src/pages/civic-center-service/components/CivicCenterForm.tsx
- frontend/src/pages/pactice-program/components/PracticeProgramForm.tsx
- frontend/src/services/practice-program/PracticeProgram.helper.ts
[C4R-964](https://wearetribus.atlassian.net/browse/C4R-964) Hide End date if period undetermined is set
> Bugfix[C4R-964] Hide end date Practice programs

- backend/src/modules/civic-center-service/dto/create-civic-center-service.dto.ts
- frontend/src/assets/locales/ro/translation.json
- frontend/src/components/RichText/RichText.tsx
- frontend/src/index.css
- frontend/src/pages/civic-center-service/components/CivicCenterForm.tsx
- frontend/src/pages/civic-center-service/components/CivicCenterServiceContent.tsx
- frontend/src/pages/civic-center-service/config/CivicCenterFormConfig.ts
[C4R-965](https://wearetribus.atlassian.net/browse/C4R-965) Wysiwyg civic center service
> [C4R-965] Integrate wysiwyg component for civic center service

- backend/src/shared/services/file-manager.service.ts
- frontend/src/services/organization/OrganizationFormDataMapper.service.ts
[C4R-484](https://wearetribus.atlassian.net/browse/C4R-484)
> fix: [C4R-484] missing error on file too large

- frontend/src/assets/locales/ro/translation.json
[C4R-958](https://wearetribus.atlassian.net/browse/C4R-958)
> fix: [C4R-958] wrong translation

- backend/src/modules/organization/services/organization-request.service.ts
[C4R-1008](https://wearetribus.atlassian.net/browse/C4R-1008)
> fix: [C4R-1008] validate phone number on step 1 of create org

- backend/src/modules/organization/dto/create-organization-request.dto.ts
[C4R-999](https://wearetribus.atlassian.net/browse/C4R-999)
> fix: [C4R-999] wrong name length validation for request admin name

- frontend/src/pages/users/components/UserList/UserList.tsx
[C4R-893](https://wearetribus.atlassian.net/browse/C4R-893)
> fix: [C4R-893] edit button displayed for super admin on user

- backend/src/modules/statistics/entities/organization-status-statistics-view.entity.ts
- backend/src/modules/statistics/services/statistics.service.ts
[C4R-954](https://wearetribus.atlassian.net/browse/C4R-954)
> fix: [C4R-954] no longer displaying data from the future

- backend/src/modules/application/services/application.service.ts
- backend/src/modules/statistics/services/statistics.service.ts
[C4R-980](https://wearetribus.atlassian.net/browse/C4R-980)
> fix: [C4R-980] number of active apps displaying all apps

- backend/src/modules/practice-program/entities/practice-program.entity.ts
[C4R-1078](https://wearetribus.atlassian.net/browse/C4R-1074)
> fix: [C4R-1078] skills and faculties would get saved in domains on PP creation

- frontend/src/index.css
https://wearetribus.atlassian.net/browse/C4R-856
> C4R-856 Action menu on table

- backend/src/modules/practice-program/services/practice-program.service.ts
- frontend/src/components/multi-select/MultiSelect.tsx
- frontend/src/components/server-select/ServerSelect.tsx
- frontend/src/pages/pactice-program/EditPracticeProgram.tsx
https://wearetribus.atlassian.net/browse/C4R-860
> C4R-860 - Select Default values

- frontend/src/components/extended-statistics-card/ExtendedStatisticsCard.tsx
https://wearetribus.atlassian.net/browse/C4R-977
> fix: [C4R-977] fix spacing on statistics cards

- frontend/src/pages/create-organziation/CreateOrganization.tsx
https://wearetribus.atlassian.net/browse/C4R-1011
> fix: [C4R-1011] fix submit of the organization creation

- frontend/src/pages/apps-store/components/ApplicationRequests.tsx
- frontend/src/pages/requests/components/RequestList.tsx
[C4R-1012](https://wearetribus.atlassian.net/browse/C4R-1012) - updated for organization requests and application requests
> fix: [C4R-1012] reset filters not resetting date

- frontend/src/pages/organization/components/OrganizationLegal/OrganizationLegal.tsx
[C4R-483](https://wearetribus.atlassian.net/browse/C4R-483)
> fix: [C4R-483] wrong filter conditions when deleting director

- frontend/src/components/line-chart/LineChart.tsx
- frontend/src/components/statistics-card/StatisticsCard.tsx
- frontend/tailwind.config.js
[C4R-955](https://wearetribus.atlassian.net/browse/C4R-955)
> fix: [C4R-955] cards not displayed properly in super admin dashboard

- frontend/src/components/Contact/Contact.tsx
- frontend/src/pages/organization/Organization.tsx
- frontend/src/pages/organization/OrganizationProfile.tsx
- frontend/src/pages/organization/components/OrganizationGeneral/OrganizationGeneral.tsx
- frontend/src/pages/requests/components/Request.tsx
[C4R-1089](https://wearetribus.atlassian.net/browse/C4R-1089)
> fix: [C4R-1089] disabled contact person fields

- frontend/src/common/helpers/format.helper.ts
- frontend/src/pages/pactice-program/components/PracticeProgramContent.tsx
[C4R-1068](https://wearetribus.atlassian.net/browse/C4R-1068)
> fix: [C4R-1068] deadline application date not being displayed

- backend/src/shared/constants/file-errors.constants.ts
- backend/src/shared/services/file-manager.service.ts
- frontend/src/assets/locales/ro/translation.json
- frontend/src/common/constants/error.constants.ts
[C4R-484](https://wearetribus.atlassian.net/browse/C4R-484)
> fix: [C4R-484] added specific size errors for logo and org statute

- backend/src/modules/application/services/application.service.ts
- backend/src/modules/application/services/user-ong-application.service.ts
- backend/src/modules/statistics/controllers/statistics.controller.ts
- backend/src/modules/statistics/services/statistics.service.ts
[C4R-980](https://wearetribus.atlassian.net/browse/C4R-980)
> fix: [C4R-980] fixed dashboard counter for number of active apps

- frontend/src/assets/locales/ro/translation.json
- frontend/src/pages/apps-store/components/AddApplication.tsx
- frontend/src/pages/apps-store/components/AddApplicationConfig.ts
- frontend/src/pages/apps-store/components/ApplicationForm.tsx
- frontend/src/pages/organization/components/OrganizationLegal/OrganizationLegal.tsx
- frontend/src/services/application/Application.service.ts
[C4R-922](https://wearetribus.atlassian.net/browse/C4R-922)
> fix: [C4R-922] removed default steps for app creation

- backend/src/modules/civic-center-service/controllers/civic-center.controller.ts
- backend/src/modules/civic-center-service/dto/get-services-filter.dto.ts
- backend/src/modules/practice-program/controllers/practice-program.controller.ts
- backend/src/modules/practice-program/dto/get-practice-programs-filter.dto.ts
- frontend/src/assets/locales/ro/translation.json
- frontend/src/pages/civic-center-service/CivicCenterServiceList.tsx
- frontend/src/pages/organization/components/OrganizationPracticePrograms/OrganizationPracticePrograms.tsx
- frontend/src/pages/pactice-program/components/PracticeProgramsList.tsx
- frontend/src/services/civic-center-service/CivicCenterService.queries.ts
- frontend/src/services/civic-center-service/CivicCenterService.service.ts
- frontend/src/services/practice-program/PracticeProgram.queries.ts
- frontend/src/services/practice-program/PracticeProgram.service.ts
[C4R-1099](https://wearetribus.atlassian.net/browse/C4R-1099) - Add organization id filters for practice programs and services
> Bugfix[C4R-1099] Filter by organization for practice programs and services

- frontend/src/components/data-table/DataTableComponent.tsx
- frontend/src/pages/application/components/ApplicationNGOList.tsx
- frontend/src/pages/apps-store/components/ApplicationListTable.tsx
- frontend/src/pages/apps-store/components/ApplicationRequests.tsx
- frontend/src/pages/civic-center-service/feedback/FeedbackList.tsx
- frontend/src/pages/organization/Organizations.tsx
- frontend/src/pages/requests/components/RequestList.tsx
- frontend/src/pages/users/components/UserList/UserList.tsx
[C4R-875](https://wearetribus.atlassian.net/browse/C4R-875)
> fix: [C4R-875] lists would use the last currentPage on page leave and return

- backend/src/modules/civic-center-service/dto/create-civic-center-service.dto.ts
- backend/src/modules/practice-program/dto/create-practice-program.dto.ts
- frontend/src/pages/civic-center-service/config/CivicCenterFormConfig.ts
- frontend/src/pages/pactice-program/config/PracticeProgramFormConfig.ts
[C4R-1115](https://wearetribus.atlassian.net/browse/C4R-1115)
> fix: [C4R-1115] description field not accepting special characters

- backend/src/common/constants/patterns.constant.ts
- backend/src/modules/organization/dto/create-organization-general.dto.ts
- frontend/src/common/helpers/format.helper.ts
- frontend/src/pages/organization/components/OrganizationGeneral/OrganizationGeneral.tsx
- frontend/src/pages/organization/components/OrganizationGeneral/OrganizationGeneralConfig.ts
[C4R-1100](https://wearetribus.atlassian.net/browse/C4R-1100)
> fix: [C4R-1100] certain fields in org general could not be emptied

- frontend/src/assets/locales/ro/translation.json
- frontend/src/pages/organization/components/OrganizationData/components/ReportSummayConfig.ts
- frontend/src/pages/pactice-program/config/PracticeProgramFormConfig.ts
[C4R-1072](https://wearetribus.atlassian.net/browse/C4R-1072)
> fix: [C4R-1072] added decimal validation for working hours for practice program

- backend/src/modules/organization/services/organization-activity.service.ts
- backend/src/modules/organization/services/organization-request.service.ts
- frontend/src/common/helpers/format.helper.ts
[C4R-1113](https://wearetribus.atlassian.net/browse/C4R-1113) Blank page request details
> [C4R-1113] Add county relation for cities response

- backend/src/modules/application/services/application.service.ts
[C4R-1118](https://wearetribus.atlassian.net/browse/C4R-1118) add missing application id condition on employee findOne query
> [C4R-1118] add missing application id condition on employee findOne query

- backend/src/modules/organization/constants/errors.constants.ts
- backend/src/modules/organization/constants/events.constants.ts
- backend/src/modules/organization/entities/organization-financial.entity.ts
- backend/src/modules/organization/events/CUI-changed-event.class.ts
- backend/src/modules/organization/services/organization-financial.service.ts
- backend/src/modules/organization/services/organization-general.service.ts
- backend/src/modules/organization/services/organization.service.ts
- backend/src/shared/services/anaf.service.ts
FIX: New financial information should be requested on CUI change during request/review process 
https://wearetribus.atlassian.net/browse/C4R-1124
> [C4R-1124] New financial information should be requested on CUI change

- frontend/src/common/helpers/format.helper.ts
- frontend/src/pages/create-organziation/components/CreateOrganizationActivity.tsx
- frontend/src/pages/organization/components/OrganizationActivity/OrganizationActivity.tsx
- frontend/src/services/organization/Organization.helper.ts
[C4R-1125](https://wearetribus.atlassian.net/browse/C4R-1125) 
- Remove optional lists when radio "false" option is selected;
- cleanup obsolete helper methods
> Bugfix[C4R-1125] The selected option is not taken into account when submit create org form

- frontend/src/components/InputField/InputField.tsx
[C4R-1060](https://wearetribus.atlassian.net/browse/C4R-1060)
> fix: [C4R-1060] added word break to input field

- backend/src/modules/user/constants/invites-filters.config.ts
- backend/src/modules/user/services/user.service.ts
- frontend/src/pages/users/components/UserInvites/UserInvites.tsx
- frontend/src/services/user/User.queries.ts
- frontend/src/services/user/User.service.ts
[C4R-1041](https://wearetribus.atlassian.net/browse/C4R-1041)
> fix: [C4R-1041] updated invited user list field searchability

- backend/src/modules/authentication/jwt.strategy.ts
- backend/src/modules/statistics/services/statistics.service.ts
- backend/src/modules/user/services/cognito.service.ts
- backend/src/modules/user/services/user.service.ts
[C4R-1041](https://wearetribus.atlassian.net/browse/C4R-1041)
> fix: [C4R-1041] refactor invited user list, used pending status to get the list

- backend/src/modules/_publicAPI/dto/contact-mail.dto.ts
- backend/src/modules/civic-center-service/dto/create-feedback.dto.ts
[C4R-1259](https://wearetribus.atlassian.net/browse/C4R-1259)
[C4R-1396](https://wearetribus.atlassian.net/browse/C4R-1396)
[C4R-1397](https://wearetribus.atlassian.net/browse/C4R-1397)
> fix: [C4R-1259] updated validations for feedback and mail contact dtos

- backend/src/modules/civic-center-service/dto/create-civic-center-service.dto.ts
- backend/src/modules/civic-center-service/services/civic-center.service.ts
- frontend/src/pages/civic-center-service/config/CivicCenterFormConfig.ts
[C4R-1371](https://wearetribus.atlassian.net/browse/C4R-1371)
> fix: [C4R-1371] made descriptions optional for the 3 types of access

- backend/src/modules/civic-center-service/services/civic-center.service.ts
- backend/src/modules/practice-program/services/practice-program.service.ts
[C4R-1401](https://wearetribus.atlassian.net/browse/C4R-1401)
> fix: [C4R-1401] find one service/program only gets active items

- backend/src/modules/statistics/services/statistics.service.ts
[C4R-952](https://wearetribus.atlassian.net/browse/C4R-952)
> fix: [C4R-952] fixed counters for admin and super admin dashboard

- frontend/src/components/chip-selection/ChipSelection.tsx
Bug [C4R-1061](https://wearetribus.atlassian.net/browse/C4R-1061)
> C4R-1061 - Fixed chip overflow

- frontend/src/components/Header/Header.tsx
- frontend/src/containers/Layout.tsx
- frontend/src/pages/dashboard/Dashboard.tsx
Bug [C4R-1198](https://wearetribus.atlassian.net/browse/C4R-1198)
> C4R-1198 - Fixed dashboard layout

- backend/src/modules/civic-center-service/services/civic-center.service.ts
- backend/src/modules/practice-program/services/practice-program.service.ts
- frontend/src/assets/locales/ro/translation.json
- frontend/src/pages/civic-center-service/config/CivicCenterFormConfig.ts
[C4R-1469](https://wearetribus.atlassian.net/browse/C4R-1469)
Also updated some translations and removed some.
> fix: [C4R-1469] ordered services and programs by date in DESC order, updated translations

- frontend/src/assets/locales/ro/translation.json
- frontend/src/pages/civic-center-service/config/CivicCenterFormConfig.ts
Bug [C4R-1363](https://wearetribus.atlassian.net/browse/C4R-1363)
> C4R-1363 - Changed rich text to 1000 max characters and error message

- frontend/src/components/InputField/InputField.tsx
- frontend/src/pages/organization/components/OrganizationFinancial/components/ExpenseReportModal.tsx
- frontend/src/pages/organization/components/OrganizationFinancial/components/IncomeReportModal.tsx
Bug [C4R-1059](https://wearetribus.atlassian.net/browse/C4R-1059)
> C4R-1059 - Fixed input sizing on mobile if not focused and on error

- frontend/src/components/chip-selection/ChipSelection.tsx
- frontend/src/components/status-radio/StatusRadio.tsx
- frontend/src/index.css
- frontend/src/pages/civic-center-service/components/CivicCenterServiceContent.tsx
- frontend/src/pages/civic-center-service/config/CivicCenterFormConfig.ts
Bug [C4R-1367](https://wearetribus.atlassian.net/browse/C4R-1367)
> Bugfix/C4R-1367 - Improper display of service card information

- backend/src/common/helpers/flatten-pulling-type.helper.ts
- backend/src/modules/_publicAPI/controllers/civic-center-public.controller.ts
- backend/src/modules/civic-center-service/constants/civic-center-filters.config.ts
- backend/src/modules/civic-center-service/interfaces/CivicCenterServiceFlat.ts
- backend/src/modules/civic-center-service/services/civic-center.service.ts
- backend/src/modules/practice-program/services/practice-program.service.ts
[C4R-1045](https://wearetribus.atlassian.net/browse/C4R-1045)
[C4R-976](https://wearetribus.atlassian.net/browse/C4R-976)
> Refactor: Add logo to search services response

- frontend/src/components/InputField/InputField.tsx
Bug [C4R-1511](https://wearetribus.atlassian.net/browse/C4R-1511)
> C4R-1511 - Fixed checkbox stretch

- backend/src/migrations/1672757115641-AgeCategoriesToArray.ts
- backend/src/modules/civic-center-service/entities/civic-center-service.entity.ts
- backend/src/modules/civic-center-service/services/civic-center.service.ts
[C4R-1509](https://wearetribus.atlassian.net/browse/C4R-1509) Filter by age category not working as expected
> Bugfix[C4R-1509] Filter by age category fix

- backend/src/modules/organization/dto/create-organization-general.dto.ts
[C4R-1527](https://wearetribus.atlassian.net/browse/C4R-1527) Unable to submit NGO form using current year as founding year
> [C4R-1527] Remove max restriction for yearCreated

- frontend/src/components/popover-menu/PopoverMenu.tsx
- frontend/src/pages/application/components/ApplicationNGOList.tsx
- frontend/src/pages/apps-store/components/ApplicationListTable.tsx
- frontend/src/pages/organization/Organizations.tsx
Bug [C4R-1536](https://wearetribus.atlassian.net/browse/C4R-1536)
Bug [C4R-1534](https://wearetribus.atlassian.net/browse/C4R-1534)
> Bugfix/C4R-1536 - Table popup fixes

- backend/src/modules/user/services/user.service.ts
https://wearetribus.atlassian.net/browse/C4R-1476
The user is no longer soft deleted, but HARD! ALso the associated apps are deleted :)
> fix:[C4R-1476] - Hard delete user together with the associated apps

- frontend/src/index.css
- frontend/src/pages/apps-store/components/ApplicationListCards.tsx
- frontend/src/pages/my-apps/components/ApplicationCard.tsx
- frontend/tailwind.config.js
[C4R-1558](https://wearetribus.atlassian.net/browse/C4R-1558)
> C4R-1588 - Card grid refactor

- backend/src/modules/organization/entities/organization-view.entity.ts
Bug [C4R-1561](https://wearetribus.atlassian.net/browse/C4R-1561)
> C4R-1561 - Fixed user count on organizations

- backend/src/common/interfaces/business-exception.ts
- backend/src/modules/_publicAPI/controllers/public-api.controller.ts
- backend/src/modules/_publicAPI/exceptions/exceptions.ts
- backend/src/modules/_publicAPI/interfaces/user-with-organization.interface.ts
- backend/src/modules/_publicAPI/public-api.module.ts
- backend/src/modules/_publicAPI/services/user-organization.service.ts
Description:
- Extend OngHub backend to allow TEO application to request initial user and organization data.
Link to Issue: [TEO-62](https://wearetribus.atlassian.net/browse/TEO-62)
> Feature[TEO-62] User and Organization data for TEO user init

- backend/src/modules/user/services/user-application.service.ts
[TEO-250](https://wearetribus.atlassian.net/browse/TEO-250)
> Bugfix[TEO-250] Admin user is restricted from accessing application

- backend/src/migrations/1684417364617-AddOrganizationGeneralAddressField.ts
- backend/src/modules/_publicAPI/interfaces/user-with-organization.interface.ts
- backend/src/modules/_publicAPI/services/user-organization.service.ts
- backend/src/modules/organization/dto/create-organization-general.dto.ts
- backend/src/modules/organization/entities/organization-general.entity.ts
- frontend/src/assets/locales/en/translation.json
- frontend/src/assets/locales/ro/translation.json
- frontend/src/pages/create-organziation/components/CreateOrganizationGeneral.tsx
- frontend/src/pages/organization/components/OrganizationGeneral/OrganizationGeneral.tsx
- frontend/src/pages/organization/components/OrganizationGeneral/OrganizationGeneralConfig.ts
- update organization general form to add address input field
- update organization create/update requests to support address field
- update ong-user request to parse activityArea and add address field
> Feature[TEO-538] Add address form field to organization general

- backend/src/modules/organization/constants/organization-filter.config.ts
- backend/src/modules/organization/entities/organization-view.entity.ts
- frontend/src/assets/locales/en/translation.json
- frontend/src/assets/locales/ro/translation.json
- frontend/src/pages/organization/interfaces/Organization.interface.ts
- frontend/src/pages/organization/table-headers/OrganizationsTable.headers.tsx
1. API change to include "Alias" in OrganizationView
2. FE Change from "ONG Name" to "ONG Alias"
> [NGOs] Change display name on NGO list

- frontend/src/pages/create-organziation/components/CreateOrganizationLegal.tsx
Fix for https://github.com/code4romania/onghub/issues/342
> fix: 342 - Fixed inconsistent buttons on organisation registration

- frontend/src/pages/organization/components/OrganizationData/table-headers/InvestorTable.headers.tsx
- frontend/src/pages/organization/components/OrganizationData/table-headers/PartnerTable.headers.tsx
- frontend/src/pages/organization/components/OrganizationData/table-headers/ReportsTable.headers.tsx
- frontend/src/pages/organization/components/OrganizationFinancial/OrganizationFinancialTableHeaders.tsx
Fix for issue https://github.com/code4romania/onghub/issues/349
> fix: 349 - Adjusted column widths on my organisation data tables

- frontend/src/components/confim-removal-modal/ConfirmationModal.tsx
- frontend/src/components/content-wrapper/ContentWrapper.tsx
- frontend/src/pages/civic-center-service/feedback/components/FeedbackViewModal.tsx
- frontend/src/pages/organization/components/OrganizationData/OrganizationData.tsx
- frontend/src/pages/organization/components/OrganizationData/components/ReportSummaryModal.tsx
- frontend/src/pages/organization/components/OrganizationLegal/components/OtherModal.tsx
Fix for issue https://github.com/code4romania/onghub/issues/376
> fix: 376 - Fixed overflowing texts

- backend/src/modules/organization/dto/update-organization-report.dto.ts
- frontend/src/pages/create-organziation/components/CreateOrganizationGeneral.tsx
- frontend/src/pages/create-organziation/components/CreateOrganizationLegal.tsx
- frontend/src/pages/create-organziation/components/CreateOrganizationUser.tsx
> Bugfix[C4R-315] Set minimum number of contractors and volunteer to 0

- frontend/src/components/InputField/InputField.tsx
Fix for issue https://github.com/code4romania/onghub/issues/324
> fix: 324 - Added eye icon on password inputs

- frontend/src/components/Header/Header.tsx
- frontend/src/index.css
- frontend/src/pages/apps-store/components/ApplicationRequests.headers.tsx
Fix for issue https://github.com/code4romania/onghub/issues/374
> fix: 374 - Added organization link in requests table

- frontend/src/index.css
> Bugfix[C4R-363] - Tables in the site look different than the designs

- frontend/src/assets/locales/en/translation.json
- frontend/src/assets/locales/ro/translation.json
- frontend/src/components/data-table-name-header/DataTableNameHeader.tsx
- frontend/src/index.css
- frontend/src/pages/application/components/headers/application-ngo-list.headers.tsx
- frontend/src/pages/apps-store/components/ApplicationList.headers.tsx
- frontend/src/pages/apps-store/components/ApplicationRequests.headers.tsx
- frontend/src/pages/civic-center-service/feedback/table-headers/FeedbackListTable.headers.tsx
- frontend/src/pages/organization/components/OrganizationApplications/table-headers/OrganizationApplicationAccessRequestTable.headers.tsx
- frontend/src/pages/organization/components/OrganizationApplications/table-headers/OrganizationApplicationsTable.headers.tsx
- frontend/src/pages/organization/components/OrganizationData/table-headers/InvestorTable.headers.tsx
- frontend/src/pages/organization/components/OrganizationData/table-headers/PartnerTable.headers.tsx
- frontend/src/pages/organization/components/OrganizationData/table-headers/ReportsTable.headers.tsx
- frontend/src/pages/organization/components/OrganizationFinancial/OrganizationFinancialTableHeaders.tsx
- frontend/src/pages/organization/components/OrganizationFinancial/components/ReportTableRow.tsx
- frontend/src/pages/organization/components/OrganizationLegal/table-headers/DirectorsTable.headers.tsx
- frontend/src/pages/organization/components/OrganizationLegal/table-headers/OthersTable.headers.tsx
- frontend/src/pages/organization/table-headers/OrganizationsTable.headers.tsx
- frontend/src/pages/requests/components/RequestList.headers.tsx
- frontend/src/pages/users/components/UserInvites/table-headers/UserInvitesTable.headers.tsx
- frontend/src/pages/users/components/UserList/table-headers/UserListTable.headers.tsx
> Feat[C4R-354] - Show full label name when user hovers over table column name

- frontend/src/components/popover-menu/PopoverMenu.tsx
> Feat[C4R-333] - User can click to on 'download list' even if there's no list to download 

- backend/src/migrations/1699889886586-SynchedAnaf.ts
- backend/src/modules/organization/constants/errors.constants.ts
- backend/src/modules/organization/controllers/organization.controller.ts
- backend/src/modules/organization/entities/organization-financial.entity.ts
- backend/src/modules/organization/services/organization-financial.service.ts
- backend/src/shared/services/anaf.service.ts
- frontend/src/assets/locales/en/translation.json
- frontend/src/pages/organization/components/OrganizationFinancial/OrganizationFinancial.tsx
- frontend/src/pages/organization/interfaces/OrganizationFinancial.interface.ts
- frontend/src/services/organization/Organization.queries.ts
- frontend/src/services/organization/Organization.service.ts
https://github.com/code4romania/onghub/issues/352
> fix: [C4R-352] add ANAF report regenerate on demand for requests

- backend/src/modules/user/constants/user-error.constants.ts
- backend/src/modules/user/services/user.service.ts
- frontend/src/pages/users/constants/error.constants.ts
> bugfix: [358] Sending an invite wouldn't work and not showing an error

- backend/src/migrations/1700316222351-UserApplicationsView.ts
- backend/src/modules/user/admin-user.controller.ts
- backend/src/modules/user/constants/user-filters.config.ts
- backend/src/modules/user/entities/user-applications-view.entity.ts
- backend/src/modules/user/profile.controller.ts
- backend/src/modules/user/repositories/user-applications-view.repository.ts
- backend/src/modules/user/services/user.service.ts
- backend/src/modules/user/user.module.ts
- frontend/src/components/data-table/DataTableComponent.tsx
- frontend/src/components/menu/Menu.tsx
- frontend/src/containers/Layout.tsx
- frontend/src/pages/apps-store/AllApplications.tsx
- frontend/src/pages/organization/OrganizationProfile.tsx
- frontend/src/pages/organization/Organizations.tsx
- frontend/src/pages/organization/table-headers/OrganizationsTable.headers.tsx
- frontend/src/pages/requests/components/RequestList.headers.tsx
- frontend/src/pages/requests/components/RequestList.tsx
- frontend/src/pages/users/Users.tsx
- frontend/src/pages/users/components/UserList/UserList.tsx
- frontend/src/pages/users/components/UserList/table-headers/UserListTable.headers.tsx
- frontend/src/pages/users/interfaces/User.interface.ts
- frontend/tailwind.config.js
Closes #359 
+ other fixes:
- prevent layout breaking while resizing due to table width 
- add onRowClick on tables where view/edit is possible (users, requests, ngos)
- smaller text on smaller resolutions (tabs)
- fix table cell widths (request list, user list, ngos list)
> bugfix: [359] Missing user's apps columns and various fixes

- frontend/src/assets/locales/en/translation.json
- frontend/src/assets/locales/ro/translation.json
- frontend/src/pages/apps-store/components/EditApplication.tsx
- frontend/src/pages/apps-store/constants/ApplicationType.enum.ts
- frontend/src/pages/create-organziation/components/CreateOrganizationActivity.tsx
- frontend/src/pages/create-organziation/components/CreateOrganizationGeneral.tsx
- frontend/src/pages/create-organziation/components/CreateOrganizationLegal.tsx
- frontend/src/pages/create-organziation/components/CreateOrganizationUser.tsx
- frontend/src/pages/organization/Organization.tsx
- frontend/src/pages/organization/components/OrganizationActivity/OrganizationActivity.tsx
- frontend/src/pages/organization/components/OrganizationData/OrganizationData.tsx
- frontend/src/pages/organization/components/OrganizationData/components/ReportSummaryModal.tsx
- frontend/src/pages/organization/components/OrganizationFinancial/OrganizationFinancial.tsx
- frontend/src/pages/organization/components/OrganizationFinancial/components/ExpenseReportModal.tsx
- frontend/src/pages/organization/components/OrganizationFinancial/components/IncomeReportModal.tsx
- frontend/src/pages/organization/components/OrganizationGeneral/OrganizationGeneral.tsx
- frontend/src/pages/organization/components/OrganizationLegal/OrganizationLegal.tsx
- frontend/src/pages/organization/components/OrganizationLegal/components/DirectorModal.tsx
- frontend/src/pages/organization/components/OrganizationLegal/components/OtherModal.tsx
- frontend/src/pages/requests/components/Request.tsx
+ synched EN with RO, as discussed with @birloiflorian 
PR for 
https://github.com/code4romania/onghub/issues/337
https://github.com/code4romania/onghub/issues/369
> fix: [C4R-369] missing translations

- frontend/src/assets/locales/en/translation.json
- frontend/src/assets/locales/ro/translation.json
- frontend/src/pages/application/constants/filter.constants.ts
- frontend/src/pages/apps-store/constants/ApplicationStatus.constant.ts
- frontend/src/pages/organization/Organizations.tsx
- frontend/src/pages/organization/constants/filters.constants.ts
- frontend/src/pages/users/components/UserList/UserList.tsx
- frontend/src/pages/users/constants/filters.constants.ts
++++ "indiferent" was my best option atm.
> fix: [C4R-357] show "all" option for filters

- frontend/src/pages/my-apps/components/ApplicationCard.tsx
!! Commented the code instead of deleting it due to the complex rule for displaying that button.
> feat: [C4R-431] commented the open button for Application Cards

- frontend/src/components/Select/Select.tsx
Fix Selects to show the checkmark also on values that come from controlled inputs, not by user input
> fix: [611] fix selected option for controlled inputs
